### ISSUE TITLE
镜像后各view的坐标问题

### ISSUE THREAD

**Issue by daoxiangcun** [OboBear/AndroidReverseView#1]
假如最初有一个button在左边，镜像后到了右边，但是必须点击左边的位置才相当于点击了button，这个问题没有处理？

**Comment by OboBear** [comment]
这个问题并没有在这个版本中解决，因为目前的这个版本只是简单的界面绘制的翻转，要做手势翻转的话需要用另外一种方法。

**Comment by OboBear** [comment]
我给ReverseLayout添加了一种点击转换的方式，还增加了一种新的更加全面简单的翻转的方式
